// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026
//  Mud.HttpUtils 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using Mud.HttpUtils.ToolSurface.Extraction;
using Mud.HttpUtils.ToolSurface.Schema;

namespace Mud.HttpUtils.ToolSurface.Emit;

/// <summary>
/// Tier C 发射器：产出参数解包类型——每枚工具特性接口一个强类型入参类型
/// （<c>{Tool}Args</c>，独立产物文件），把执行器方法首部逐参读取收敛为<b>一次</b> <c>Unpack</c> 调用。
/// </summary>
/// <remarks>
/// <para>
/// 移植自上游 <c>Mud.Feishu.AI.Tools.Emit.ToolArgsEmitter</c>（设计文档 §5.1 第 4 条输出路径）。泛化点：
/// <list type="bullet">
/// <item>owner 门槛：上游 <c>SchemaEmitter.ToolNamesOwnerAssembly</c> → 单一剖面槽
/// <see cref="SdkToolProfileModel.OwnerAssembly"/>（§5.2-2，上游同值三常量已收敛）；</item>
/// <item>产物命名空间：上游 <c>NamespaceName = "Mud.Feishu.AI.FeishuTools"</c> →
/// <see cref="SdkToolProfileModel.ContractNamespace"/>（§4.2 第 10 项；恰与 owner 门槛值同串，
/// 但语义不同——门槛是程序集名，此处是产物落点命名空间，分别独立消费各自的槽）；</item>
/// <item>产物目录 hintName 前缀：<c>FeishuToolArgs</c> → <c>{ProductPrefix}Args</c>；</item>
/// <item>诊断：MUDFT020/021 → <see cref="ToolSurfaceDiagnostics.Factory"/> 槽位 20/21。</item>
/// </list>
/// </para>
/// <para>
/// <b>为什么值得生成</b>：参数名在「接口签名（C# 参数名 = 参数特性声明名）」与
/// 「执行器里的字符串字面量」两处独立维护，两者漂移的唯一表现是<b>运行期</b>
/// <c>ArgumentException: 缺少必填参数 x</c>——编译期零保证。生成 <c>Unpack</c> 后字段名由接口派生，
/// 改名即执行器编译失败（从运行期漂移降级为编译期错误）。
/// </para>
/// <para>
/// <b>解包映射表是引擎机制</b>（§5.2-1）：<see cref="TryResolveReader"/> 的「类型 → 读取器」表保留在
/// 引擎内，扩展点从"改某个 SDK 生态源码"变为"改引擎源码 + 加引擎级测试"。读取器指向的
/// <c>ToolArgs</c> helper 集由 owner 程序集手写提供（产物只引用其类型名，不复制其实现）。
/// </para>
/// <para>
/// <b>不生成执行器方法体</b>：白名单投影、filter/sort 解析、RFC3339 转换、dry_run 摘要等业务逻辑
/// 仍由人写——生成器只搬运「从参数字典取值」这一机械动作。
/// </para>
/// </remarks>
internal static class ToolArgsEmitter
{
    /// <summary>类型名后缀（<c>bitable.list_tables</c> → <c>BitableListTablesArgs</c>）。</summary>
    public const string TypeSuffix = "Args";

    /// <summary>解包方法名。</summary>
    public const string UnpackMethodName = "Unpack";

    /// <summary>工具名常量名（契约守卫据此把类型映射回工具名，无需在测试里复刻 PascalCase 规则）。</summary>
    public const string ToolNameConstant = "ToolName";

    /// <summary>产物目录名（每类型一个文件，hintName 前缀与 <c>{P}Names.g.cs</c> 同体例分组）。</summary>
    public static string OutputFolder(SdkToolProfileModel profile)
        => profile.ProductPrefix + TypeSuffix;

    /// <summary>
    /// 发射参数解包产物（仅名字契约所有者程序集；无工具或不满足门槛时不产出）。
    /// 每枚 <c>{Tool}Args</c> 类型一个独立产物文件（<c>{P}Args/{TypeName}.g.cs</c>）。
    /// </summary>
    /// <param name="context">源产出上下文。</param>
    /// <param name="models">Tier C 模型集合。</param>
    /// <param name="profile">当前剖面（owner 门槛 / 产物命名空间 / 目录前缀槽的唯一来源）。</param>
    /// <param name="assemblyName">当前编译的程序集名（决定是否发射）。</param>
    /// <param name="factory">当前剖面的诊断工厂（槽位 020/021 描述符）。</param>
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<ToolSchemaModel> models,
        SdkToolProfileModel profile,
        string? assemblyName,
        ToolSurfaceDiagnostics.Factory factory)
    {
        try
        {
            if (models.IsEmpty
                || !string.Equals(assemblyName, profile.OwnerAssembly, StringComparison.Ordinal))
            {
                return;
            }

            foreach (var model in models.OrderBy(static m => m.Entry.ToolName, StringComparer.Ordinal))
            {
                // 不支持的参数形态已由槽位 020 上报（构建已失败），此处不产出半成品类型造成二次噪声。
                if (BuildPlan(context, model, profile, factory) is not { } plan)
                {
                    continue;
                }

                TransitiveCodeGenerator.AddSourceValidated(
                    context,
                    HintName(plan.TypeName, profile),
                    RenderArgsType(plan, profile));
            }
        }
        catch (Exception ex)
        {
            GeneratorDebugLogger.LogError(nameof(ToolArgsEmitter), ex);
        }
    }

    /// <summary>产物 hintName：每类型一个文件，按产物目录分组（<c>BitableListTablesArgs</c> → <c>{P}Args/BitableListTablesArgs.g.cs</c>）。</summary>
    public static string HintName(string typeName, SdkToolProfileModel profile)
        => $"{OutputFolder(profile)}/{typeName}.g.cs";

    /// <summary>渲染单个 <c>{Tool}Args</c> 类型的完整产物源文件（文件头 + 命名空间 + 一个类型）。</summary>
    private static string RenderArgsType(ArgsPlan plan, SdkToolProfileModel profile)
    {
        var source = new StringBuilder();
        source.Line($"// <auto-generated> 由 {GeneratedCodeMarker.GeneratorName(profile)} 编译期产出，禁止手工修改 </auto-generated>");
        source.Line("#nullable enable");
        source.Line("#pragma warning disable CS1591 // 生成代码不逐一补 XML 注释");
        source.Line($"namespace {profile.ContractNamespace}");
        source.Line("{");
        WriteArgsType(source, plan, profile);
        source.Line("}");
        return source.ToString();
    }

    // ────────── 计划构造（唯一的上报点） ──────────

    /// <summary>把一枚工具的参数声明翻译为解包计划（含字段类型与读取表达式）。</summary>
    /// <returns>解包计划；含不可映射参数时返回 <see langword="null"/>（已上报槽位 020）。</returns>
    private static ArgsPlan? BuildPlan(
        SourceProductionContext context,
        ToolSchemaModel model,
        SdkToolProfileModel profile,
        ToolSurfaceDiagnostics.Factory factory)
    {
        var entry = model.Entry;
        var fields = new List<ArgsField>(entry.Parameters.Count);
        var unsupported = false;

        foreach (var parameter in entry.Parameters)
        {
            if (parameter.IsRequired && parameter.IsNullable)
            {
                // 槽位 021 上报点：Schema 会把它放进 required，而解包读的是必填读取器——
                // 该组合只在「必填声明标注在可空参数上」时出现，属声明自相矛盾。
                factory.Report(context, ToolSurfaceDiagnostics.SlotRequiredNullableConflict, null,
                    entry.ToolName, parameter.Name);
            }

            if (!TryResolveReader(parameter, out var fieldType, out var reader))
            {
                // 槽位 020 上报点（扩展触发点）：新增参数类型时须先在 owner 侧 ToolArgs 补 helper 并登记映射。
                factory.Report(context, ToolSurfaceDiagnostics.SlotUnpackMappingMissing, null,
                    entry.ToolName, parameter.Name, parameter.CsharpType);
                unsupported = true;
                continue;
            }

            fields.Add(new ArgsField(
                name: parameter.Name,
                fieldName: SchemaEmitter.BuildNameConstant(parameter.Name),
                fieldType: fieldType,
                reader: reader,
                description: parameter.DocDescription));
        }

        return unsupported
            ? null
            : new ArgsPlan(
                toolName: entry.ToolName,
                typeName: SchemaEmitter.BuildNameConstant(entry.ToolName) + TypeSuffix,
                fields: fields,
                closedSetMaps: RenderClosedSetMaps(entry.Parameters));
    }

    /// <summary>
    /// 参数 → 解包读取器映射表（唯一真相源；与 owner 程序集 <c>ToolArgs</c> 的 helper 集必须一一对应）。
    /// </summary>
    /// <remarks>
    /// <para>
    /// 只映射<b>当前工具面真实存在的形态</b>：<c>string</c> / <c>string?</c> / <c>string[]</c> /
    /// <c>string[]?</c> / <c>int?</c> / <c>bool?</c>（上游 61 枚工具逐一核对；计数以本仓规模守卫实测口径为准）。
    /// </para>
    /// <para>
    /// <c>int</c> 必填与可选映射均提供（<c>RequireInt</c> / <c>OptionalInt</c>）；
    /// <c>bool</c> 仅提供可选映射（当前无工具声明必填布尔参数）。
    /// </para>
    /// </remarks>
    private static bool TryResolveReader(CapabilityParameter parameter, out string fieldType, out string reader)
    {
        var name = JsonText.ToCSharpLiteral(parameter.Name);
        var isRequired = parameter.IsRequired;

        // R5 / F-2：显式声明的取值闭集优先于类型推导。
        //
        // ⚠️ 关键：Schema 侧渲染的是**闭集成员的字面量**（enum 名或常量类常量名），
        // 而参数的 C# 类型是 `int` / 某个 enum。二者口径必须一致，否则模型按 Schema 传名字、
        // 读取器却按数值解析 ⇒ 恒失败。故此处**不复用**下面的 NormalizeTypeName 分支。
        if (TryResolveClosedSetReader(parameter, name, isRequired, out fieldType, out reader))
        {
            return true;
        }

        switch (NormalizeTypeName(parameter.CsharpType))
        {
            case "string":
                if (isRequired)
                {
                    fieldType = "string";
                    reader = $"ToolArgs.RequireString(args, {name})";
                }
                else
                {
                    fieldType = "string?";
                    reader = $"ToolArgs.OptionalString(args, {name})";
                }

                return true;

            case "string[]":
                // 必填数组用 RequireStringArray（= OptionalStringArray + 缺失/为空即抛）——与 RequireString 同构。
                if (isRequired)
                {
                    fieldType = "string[]";
                    reader = $"ToolArgs.RequireStringArray(args, {name})";
                }
                else
                {
                    fieldType = "string[]?";
                    reader = $"ToolArgs.OptionalStringArray(args, {name})";
                }

                return true;

            case "int":
                if (isRequired)
                {
                    fieldType = "int";
                    reader = $"ToolArgs.RequireInt(args, {name})";
                }
                else
                {
                    fieldType = "int?";
                    reader = $"ToolArgs.OptionalInt(args, {name})";
                }

                return true;

            case "bool" when !isRequired:
                fieldType = "bool?";
                reader = $"ToolArgs.OptionalBool(args, {name})";
                return true;

            default:
                fieldType = string.Empty;
                reader = string.Empty;
                return false;
        }
    }

    /// <summary>
    /// 渲染取值闭集的读取器（R5 / F-2）。
    /// </summary>
    /// <returns>
    /// <see langword="true"/> 已产出 <paramref name="reader"/>；<see langword="false"/>
    /// "本参数无闭集或闭集不可解"⇒ 调用方<b>回退到类型推导分支</b>（随后可能被槽位 020 拦下）。
    /// </returns>
    /// <remarks>
    /// <b>两类闭集（R5 / R-4）</b>：
    /// <list type="number">
    /// <item><b>C# enum</b>：参数 C# 类型<b>就是</b>该 enum（同名）⇒
    /// <c>ToolArgs.RequireEnum&lt;TEnum&gt;</c> / <c>OptionalEnum&lt;TEnum&gt;</c>，
    /// 泛型 + <c>Enum.TryParse</c>，AOT 安全；</item>
    /// <item><b>常量类</b>（<c>static class</c> + <c>const int</c>）：
    /// 参数类型是 <c>int</c> ⇒ 只能按名字映射，用
    /// <c>ToolArgs.RequireNamedInt</c> / <c>OptionalNamedInt</c>，
    /// 映射表由 <see cref="RenderClosedSetMaps"/> 发射为 <c>static readonly Dictionary</c>。</item>
    /// </list>
    /// </remarks>
    private static bool TryResolveClosedSetReader(
        CapabilityParameter parameter,
        string nameLiteral,
        bool isRequired,
        out string fieldType,
        out string reader)
    {
        fieldType = string.Empty;
        reader = string.Empty;

        if (string.IsNullOrEmpty(parameter.EnumTypeFullName) || string.IsNullOrEmpty(parameter.EnumMembers))
        {
            return false;
        }

        // 真实 C# enum：参数类型与闭集类型同名。
        if (string.Equals(
                NormalizeTypeName(parameter.CsharpType),
                NormalizeTypeName(parameter.EnumTypeFullName!),
                StringComparison.Ordinal))
        {
            var enumType = "global::" + parameter.EnumTypeFullName;
            fieldType = isRequired ? enumType : $"{enumType}?";
            reader = isRequired
                ? $"ToolArgs.RequireEnum<{enumType}>(args, {nameLiteral})"
                : $"ToolArgs.OptionalEnum<{enumType}>(args, {nameLiteral})";
            return true;
        }

        // 常量类 + 整型参数：按常量名映射。
        if (NormalizeTypeName(parameter.CsharpType) is not ("int" or "long" or "short" or "string"))
        {
            return false;
        }

        var map = ClosedSetMapAccess(parameter.EnumTypeFullName!);

        // R5 / F-5：闭集声明为 `string` 时，模型侧传**名字**（Schema 是
        // `{"type":"string","enum":[…]}`），而 Args 字段必须是**整型**（SDK 要数字）——
        // 两者由同一个 `RequireNamedInt` 衔接。若沿用声明类型 `string`，字段会变成字符串，
        // 与生成器后续按整型使用它的假设冲突。
        var declaredType = NormalizeTypeName(parameter.CsharpType);
        fieldType = declaredType == "string"
            ? (isRequired ? "int" : "int?")
            : parameter.CsharpType;

        reader = isRequired
            ? $"ToolArgs.RequireNamedInt(args, {nameLiteral}, {map})"
            : $"ToolArgs.OptionalNamedInt(args, {nameLiteral}, {map})";
        return true;
    }

    /// <summary>成员表分隔符（netstandard2.0 无 <c>Split(char, …)</c> 重载）。</summary>
    private static readonly char[] SemicolonSeparators = [';'];

    /// <summary>常量类映射表在生成类内的字段名（由 <c>RenderClosedSetMaps</c> 发射）。</summary>
    private static string ClosedSetMapAccess(string enumTypeFullName)
        => "__closedSet_" + enumTypeFullName.Replace("global::", string.Empty).Replace('.', '_');

    /// <summary>
    /// 为参数列表中<b>每个常量类闭集</b>发射一个
    /// <c>private static readonly IReadOnlyDictionary&lt;string,int&gt;</c> 映射表。
    /// </summary>
    /// <remarks>
    /// <b>为什么必须发射</b>：模型按 Schema 里的<b>常量名</b>传值，而 SDK 要<b>整型平台值</b>；
    /// 不发射这层映射就会"Schema 收名字、读取器收数字"⇒ 该参数<b>恒失败</b>。
    /// <c>static readonly</c> ⇒ <b>零反射</b>（AOT 纪律 IL2026/IL3050 = 0）。
    /// 成员表取自 <see cref="CapabilityParameter.EnumMembers"/>（<c>"name=value;…"</c>）。
    /// </remarks>
    private static string RenderClosedSetMaps(IReadOnlyList<CapabilityParameter> parameters)
    {
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var builder = new StringBuilder();

        foreach (var parameter in parameters)
        {
            if (string.IsNullOrEmpty(parameter.EnumTypeFullName) || string.IsNullOrEmpty(parameter.EnumMembers))
            {
                continue;
            }

            // 真实 C# enum 不需要映射表（泛型 Enum.TryParse 直接按名解析）。
            if (string.Equals(
                    NormalizeTypeName(parameter.CsharpType),
                    NormalizeTypeName(parameter.EnumTypeFullName!),
                    StringComparison.Ordinal))
            {
                continue;
            }

            var access = ClosedSetMapAccess(parameter.EnumTypeFullName!);
            if (!emitted.Add(access))
            {
                continue;
            }

            builder.Append("    private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, int> ")
                .Append(access)
                .Append(" = new global::System.Collections.Generic.Dictionary<string, int>(StringComparer.Ordinal)\n    {\n");

            // netstandard2.0：无 string.Split(char, StringSplitOptions) 重载、无 Range/Index ⇒ 用 char[] + Substring。
            foreach (var pair in parameter.EnumMembers!.Split(SemicolonSeparators, StringSplitOptions.RemoveEmptyEntries))
            {
                var separator = pair.IndexOf('=');
                if (separator <= 0)
                {
                    continue;
                }

                var key = JsonText.Quote(pair.Substring(0, separator));
                var value = pair.Substring(separator + 1);
                if (!int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var number))
                {
                    // 非整型常量（如 const string）——本仓闭集只用整型；出现即跳过该键而非产出错代码。
                    continue;
                }

                builder.Append("        [").Append(key).Append("] = ")
                    .Append(number.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(",\n");
            }

            builder.Append("    };\n");
        }

        return builder.ToString();
    }

    /// <summary>
    /// 归一化 C# 类型显示名（去 <c>?</c>、别名与 CLR 名统一）——<c>ToDisplayString()</c> 的
    /// 可空引用注解与 <c>UseSpecialTypes</c> 选项跨版本有差异，按名匹配必须容错两侧写法。
    /// </summary>
    private static string NormalizeTypeName(string csharpType)
    {
        var name = csharpType.Trim().TrimEnd('?').Trim();
        return name switch
        {
            "System.String" or "String" => "string",
            "System.String[]" or "String[]" => "string[]",
            "System.Int32" or "Int32" => "int",
            "System.Boolean" or "Boolean" => "bool",
            _ => name,
        };
    }

    // ────────── 产物渲染 ──────────

    private static void WriteArgsType(StringBuilder source, ArgsPlan plan, SdkToolProfileModel profile)
    {
        source.Line($"    /// <summary>{XmlEscape(plan.ToolName)} 的模型入参（编译期从 [{profile.ToolAttributeName}] / [{profile.ParameterAttributeName}] 声明派生）。</summary>");
        source.Line($"    {GeneratedCodeMarker.Attribute(profile)}");
        source.Line($"    internal sealed class {plan.TypeName}");
        source.Line("    {");
        source.Line($"        /// <summary>工具名契约常量（与 <c>{profile.ProductPrefix}Names</c> 同源；契约守卫据此把本类型映射回工具名）。</summary>");
        source.Line($"        internal const string {ToolNameConstant} = {JsonText.ToCSharpLiteral(plan.ToolName)};");

        // R5 / F-2：常量类闭集的"常量名 → 平台整数值"映射表（零反射；AOT 安全）。
        if (!string.IsNullOrEmpty(plan.ClosedSetMaps))
        {
            source.Append(plan.ClosedSetMaps);
            source.Line();
        }

        var locals = plan.Fields.Select(static f => LocalName(f.FieldName)).ToArray();

        if (plan.Fields.Count > 0)
        {
            source.Line();
            source.Line($"        {GeneratedCodeMarker.Attribute(profile)}");
            source.Line($"        public {plan.TypeName}({string.Join(", ", plan.Fields.Select(static (f, i) => f.FieldType + " " + LocalName(f.FieldName)))})");
            source.Line("        {");
            for (var i = 0; i < plan.Fields.Count; i++)
            {
                source.Line($"            {plan.Fields[i].FieldName} = {locals[i]};");
            }

            source.Line("        }");

            foreach (var field in plan.Fields)
            {
                source.Line();
                if (!string.IsNullOrWhiteSpace(field.Description))
                {
                    source.Line($"        /// <summary>{XmlEscape(field.Description!)}</summary>");
                }

                source.Line($"        {GeneratedCodeMarker.Attribute(profile)}");
                source.Line($"        public {field.FieldType} {field.FieldName} {{ get; }}");
            }
        }

        source.Line();
        source.Line("        /// <summary>从模型 tool_call 参数字典解包为强类型参数（与参数特性声明同源，编译期生成）。</summary>");
        source.Line("        /// <exception cref=\"global::System.ArgumentException\">必填参数缺失或为空。</exception>");
        source.Line($"        {GeneratedCodeMarker.Attribute(profile)}");
        source.Line($"        public static {plan.TypeName} {UnpackMethodName}(global::System.Collections.Generic.IReadOnlyDictionary<string, object?> args)");
        source.Line("        {");
        foreach (var field in plan.Fields)
        {
            source.Line($"            var {LocalName(field.FieldName)} = {field.Reader};");
        }

        source.Line(plan.Fields.Count == 0
            ? $"            return new {plan.TypeName}();"
            : $"            return new {plan.TypeName}({string.Join(", ", locals)});");
        source.Line("        }");
        source.Line("    }");
    }

    /// <summary>字段名 → 局部变量名（首字母小写；<c>AppToken</c> → <c>appToken</c>）。</summary>
    private static string LocalName(string fieldName)
        => char.ToLowerInvariant(fieldName[0]) + fieldName.Substring(1);

    /// <summary>XML 文档文本转义（参数说明含 <c>&amp;</c>/<c>&lt;</c>/<c>&gt;</c> 时不得破坏产物）。</summary>
    private static string XmlEscape(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    // ────────── 计划模型 ──────────

    /// <summary>一枚工具的解包计划。</summary>
    private sealed class ArgsPlan
    {
        public ArgsPlan(string toolName, string typeName, IReadOnlyList<ArgsField> fields, string closedSetMaps = "")
        {
            ToolName = toolName;
            TypeName = typeName;
            Fields = fields;
            ClosedSetMaps = closedSetMaps;
        }

        /// <summary>
        /// R5 / F-2：常量类闭集的"常量名 → 平台整数值"映射表源码（<c>static readonly Dictionary</c>）。
        /// 为空串表示本工具无常量类闭集参数——此时产物里不应出现任何 <c>__closedSet_*</c> 字段。
        /// </summary>
        public string ClosedSetMaps { get; }

        public string ToolName { get; }

        public string TypeName { get; }

        public IReadOnlyList<ArgsField> Fields { get; }
    }

    /// <summary>一个参数的解包计划。</summary>
    private sealed class ArgsField
    {
        public ArgsField(string name, string fieldName, string fieldType, string reader, string? description)
        {
            Name = name;
            FieldName = fieldName;
            FieldType = fieldType;
            Reader = reader;
            Description = description;
        }

        /// <summary>模型可见参数名（snake_case）。</summary>
        public string Name { get; }

        /// <summary>PascalCase 字段名。</summary>
        public string FieldName { get; }

        /// <summary>字段类型（含可空标注）。</summary>
        public string FieldType { get; }

        /// <summary>解包读取表达式。</summary>
        public string Reader { get; }

        /// <summary>参数说明（XML <c>&lt;param&gt;</c> 或参数特性）。</summary>
        public string? Description { get; }
    }
}
