// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2025   
//  Mud.CodeGenerator 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using Mud.HttpUtils.Generators.Base;
using Mud.HttpUtils.Generators.Context;

namespace Mud.HttpUtils.Generators.Implementation;

/// <summary>
/// 类结构生成器，负责生成类的文件头部、命名空间、类声明
/// </summary>
internal class ClassStructureGenerator : ICodeFragmentGenerator
{
    private readonly INamedTypeSymbol _interfaceSymbol;

    public ClassStructureGenerator(INamedTypeSymbol interfaceSymbol)
    {
        _interfaceSymbol = interfaceSymbol;
    }

    public void Generate(StringBuilder codeBuilder, GeneratorContext context)
    {
        GenerateFileHeader(codeBuilder);
        GenerateUsingDirectives(codeBuilder, context);
        GenerateNamespaceDeclaration(codeBuilder, context);
        GenerateClassDeclaration(codeBuilder, context);
    }

    private void GenerateFileHeader(StringBuilder codeBuilder)
    {
        codeBuilder.AppendLine("// <auto-generated/>");
        codeBuilder.AppendLine("// 此代码由Mud源生成器自动生成，请勿手动修改");
        codeBuilder.AppendLine();
        codeBuilder.AppendLine("#nullable enable");
        codeBuilder.AppendLine();
    }

    private void GenerateUsingDirectives(StringBuilder codeBuilder, GeneratorContext context)
    {
        codeBuilder.AppendLine("using System;");
        codeBuilder.AppendLine("using System.Web;");
        codeBuilder.AppendLine("using System.Net.Http;");
        codeBuilder.AppendLine("using System.Text;");
        codeBuilder.AppendLine("using System.Text.Json;");
        codeBuilder.AppendLine("using System.Threading.Tasks;");
        codeBuilder.AppendLine("using Microsoft.Extensions.Logging;");
        codeBuilder.AppendLine("using Microsoft.Extensions.Options;");
        codeBuilder.AppendLine("using Mud.HttpUtils;");
        codeBuilder.AppendLine();
    }

    private void GenerateNamespaceDeclaration(StringBuilder codeBuilder, GeneratorContext context)
    {
        codeBuilder.AppendLine($"namespace {context.NamespaceName}".Trim());
        codeBuilder.AppendLine("{");
    }

    private void GenerateClassDeclaration(StringBuilder codeBuilder, GeneratorContext context)
    {
        string classKeyword = context.Configuration.IsAbstract ? "abstract partial class" : "partial class";

        string inheritance = string.Empty;
        if (context.HasInheritedFrom)
        {
            inheritance = $" : {context.Configuration.InheritedFrom}, {_interfaceSymbol.Name}";
        }
        else
        {
            inheritance = $" : {_interfaceSymbol.Name}";
        }

        codeBuilder.AppendLine($"    {GeneratedCodeConsts.HttpGeneratedCodeAttribute}");
        codeBuilder.AppendLine($"    internal {classKeyword} {context.ClassName}{inheritance}");
        codeBuilder.AppendLine("    {");
    }
}
