using Microsoft.Extensions.Options;
using System.Linq;
using System.Security.Cryptography;

namespace Mud.HttpUtils.Tests;

public class AesEncryptionProviderTests
{
    private static IEncryptionProvider CreateProvider(byte[]? key = null, byte[]? iv = null)
    {
        var options = new AesEncryptionOptions
        {
            Key = key ?? Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng=="),
            IV = iv ?? Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng==")
        };
        return new DefaultAesEncryptionProvider(Options.Create(options));
    }

    #region DefaultAesEncryptionProvider Tests

    [Fact]
    public void Encrypt_WithNullPlainText_ShouldReturnEmptyString()
    {
        var provider = CreateProvider();

        var result = provider.Encrypt(null!);

        result.Should().BeEmpty();
    }

    [Fact]
    public void Encrypt_WithEmptyPlainText_ShouldReturnEmptyString()
    {
        var provider = CreateProvider();

        var result = provider.Encrypt(string.Empty);

        result.Should().BeEmpty();
    }

    [Fact]
    public void Encrypt_WithValidPlainText_ShouldReturnNonEmptyString()
    {
        var provider = CreateProvider();

        var result = provider.Encrypt("Hello World");

        result.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void Decrypt_WithNullCipherText_ShouldReturnEmptyString()
    {
        var provider = CreateProvider();

        var result = provider.Decrypt(null!);

        result.Should().BeEmpty();
    }

    [Fact]
    public void Decrypt_WithEmptyCipherText_ShouldReturnEmptyString()
    {
        var provider = CreateProvider();

        var result = provider.Decrypt(string.Empty);

        result.Should().BeEmpty();
    }

    [Fact]
    public void Encrypt_AndDecrypt_ShouldReturnOriginalText()
    {
        var provider = CreateProvider();
        var originalText = "Hello, 世界! @#$%";

        var encrypted = provider.Encrypt(originalText);
        var decrypted = provider.Decrypt(encrypted);

        decrypted.Should().Be(originalText);
    }

    [Fact]
    public void Encrypt_WithDifferentKeys_ShouldReturnDifferentResults()
    {
        var provider1 = CreateProvider(key: Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng=="));
        var provider2 = CreateProvider(key: Convert.FromBase64String("QUJDREVGR0hJSktMTU5PUA=="));

        var result1 = provider1.Encrypt("test");
        var result2 = provider2.Encrypt("test");

        result1.Should().NotBe(result2);
    }

    [Fact]
    public void Encrypt_SameTextTwice_ShouldReturnDifferentCiphertext()
    {
        var provider = CreateProvider();

        var result1 = provider.Encrypt("test");
        var result2 = provider.Encrypt("test");

        result1.Should().NotBe(result2);
    }

    [Fact]
    public void Constructor_WithNullOptions_ShouldThrowArgumentNullException()
    {
        var act = () => new DefaultAesEncryptionProvider(null!);

        act.Should().Throw<ArgumentNullException>();
    }

    #endregion

    #region AesEncryptionOptions Tests

    [Fact]
    public void Validate_WithValidKey16Bytes_ShouldNotThrow()
    {
        var options = new AesEncryptionOptions
        {
            Key = new byte[16],
            IV = new byte[16]
        };

        var act = () => options.Validate();

        act.Should().NotThrow();
    }

    [Fact]
    public void Validate_WithValidKey24Bytes_ShouldNotThrow()
    {
        var options = new AesEncryptionOptions
        {
            Key = new byte[24],
            IV = new byte[16]
        };

        var act = () => options.Validate();

        act.Should().NotThrow();
    }

    [Fact]
    public void Validate_WithValidKey32Bytes_ShouldNotThrow()
    {
        var options = new AesEncryptionOptions
        {
            Key = new byte[32],
            IV = new byte[16]
        };

        var act = () => options.Validate();

        act.Should().NotThrow();
    }

    [Fact]
    public void Validate_WithInvalidKeyLength_ShouldThrowInvalidOperationException()
    {
        var options = new AesEncryptionOptions
        {
            Key = new byte[10],
            IV = new byte[16]
        };

        var act = () => options.Validate();

        act.Should().Throw<InvalidOperationException>()
            .WithMessage("*AES Key 长度*");
    }

    [Fact]
    public void Validate_WithInvalidIVLength_ShouldNotThrowSinceIVIsAutoGenerated()
    {
        // IV 在 v1.8.0 起自动随机生成，Validate 不再校验 IV 长度
        var options = new AesEncryptionOptions
        {
            Key = new byte[16],
            IV = new byte[10]
        };

        var act = () => options.Validate();

        act.Should().NotThrow();
    }

    [Fact]
    public void Validate_WithNullKey_ShouldThrowInvalidOperationException()
    {
        var options = new AesEncryptionOptions
        {
            Key = null!,
            IV = new byte[16]
        };

        var act = () => options.Validate();

        act.Should().Throw<InvalidOperationException>();
    }

    [Fact]
    public void Validate_WithNullIV_ShouldNotThrow()
    {
        var options = new AesEncryptionOptions
        {
            Key = new byte[16],
#pragma warning disable CS0618
            IV = null!
#pragma warning restore CS0618
        };

        var act = () => options.Validate();

        act.Should().NotThrow();
    }

    [Fact]
    public void SectionName_ShouldBeMudHttpAesEncryption()
    {
        AesEncryptionOptions.SectionName.Should().Be("MudHttpAesEncryption");
    }

    #endregion

    #region DefaultAesEncryptionProvider.Dispose Tests

    private static DefaultAesEncryptionProvider CreateDisposableProvider(byte[]? key = null, byte[]? iv = null)
    {
        var options = new AesEncryptionOptions
        {
            Key = key ?? Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng=="),
            IV = iv ?? Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng==")
        };
        return new DefaultAesEncryptionProvider(Options.Create(options));
    }

    [Fact]
    public void Dispose_CalledOnce_ShouldNotThrow()
    {
        var provider = CreateDisposableProvider();

        var act = () => provider.Dispose();

        act.Should().NotThrow();
    }

    [Fact]
    public void Dispose_CalledMultipleTimes_ShouldNotThrow()
    {
        var provider = CreateDisposableProvider();

        provider.Dispose();
        var act = () => provider.Dispose();

        act.Should().NotThrow();
    }

    [Fact]
    public void Encrypt_AfterDispose_ShouldThrowObjectDisposedException()
    {
        var provider = CreateDisposableProvider();
        provider.Dispose();

        var act = () => provider.Encrypt("test");

        act.Should().Throw<ObjectDisposedException>();
    }

    [Fact]
    public void Decrypt_AfterDispose_ShouldThrowObjectDisposedException()
    {
        var provider = CreateDisposableProvider();
        var encrypted = provider.Encrypt("test");
        provider.Dispose();

        var act = () => provider.Decrypt(encrypted);

        act.Should().Throw<ObjectDisposedException>();
    }

    [Fact]
    public void EncryptBytes_AfterDispose_ShouldThrowObjectDisposedException()
    {
        var provider = CreateDisposableProvider();
        provider.Dispose();

        var act = () => provider.EncryptBytes(new byte[16]);

        act.Should().Throw<ObjectDisposedException>();
    }

    [Fact]
    public void DecryptBytes_AfterDispose_ShouldThrowObjectDisposedException()
    {
        var provider = CreateDisposableProvider();
        var encrypted = provider.EncryptBytes(new byte[16]);
        provider.Dispose();

        var act = () => provider.DecryptBytes(encrypted);

        act.Should().Throw<ObjectDisposedException>();
    }

    #endregion

    #region AesEncryptionOptions.ClearSensitiveData Tests

    [Fact]
    public void ClearSensitiveData_ShouldZeroOutKeyAndIV()
    {
        var options = new AesEncryptionOptions
        {
            Key = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 },
            IV = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 }
        };

        options.ClearSensitiveData();

        options.Key.Should().BeEmpty();
        options.IV.Should().BeEmpty();
    }

    [Fact]
    public void ClearSensitiveData_CalledMultipleTimes_ShouldNotThrow()
    {
        var options = new AesEncryptionOptions
        {
            Key = new byte[16],
            IV = new byte[16]
        };

        options.ClearSensitiveData();
        var act = () => options.ClearSensitiveData();

        act.Should().NotThrow();
    }

    #endregion

    #region M2-#7 认证加密回归 (T-7.x)

    /// <summary>
    /// T-7.1 / T-7.4 验收：认证加密密文必须带版本前缀。
    /// net8+（AesGcm 可用）→ 0x02；否则 → 0x03（CBC+HMAC）。
    /// </summary>
    [Fact]
    public void AuthenticatedEncryption_Encrypt_ProducesVersionPrefix()
    {
        var provider = CreateProvider();
        var expected = AesGcm.IsSupported ? (byte)0x02 : (byte)0x03;

        var bytes = Convert.FromBase64String(provider.Encrypt("test"));

        bytes[0].Should().Be(expected);
    }

    /// <summary>
    /// T-7 验收：翻转密文任意 1 bit → 解密抛 <see cref="CryptographicException"/>（而非返回乱文）。
    /// 末字节属于密文体：GCM tag 校验失败 / CBC+HMAC MAC 校验失败。
    /// </summary>
    [Fact]
    public void AuthenticatedEncryption_FlipCiphertextBit_ThrowsCryptographicException()
    {
        var provider = CreateProvider();
        var bytes = Convert.FromBase64String(provider.Encrypt("secret payload"));
        bytes[^1] ^= 0x01;

        var act = () => provider.DecryptBytes(bytes);

        act.Should().Throw<CryptographicException>();
    }

    /// <summary>
    /// T-7 验收（续）：翻转 nonce/IV 字节（下标 1）→ GCM tag / HMAC MAC 均覆盖该字节 → 解密抛异常。
    /// </summary>
    [Fact]
    public void AuthenticatedEncryption_FlipNonceBit_ThrowsCryptographicException()
    {
        var provider = CreateProvider();
        var bytes = Convert.FromBase64String(provider.Encrypt("secret payload"));
        bytes[1] ^= 0x01;

        var act = () => provider.DecryptBytes(bytes);

        act.Should().Throw<CryptographicException>();
    }

    /// <summary>
    /// T-7.3 验收：v3（CBC + HMAC-SHA256 Encrypt-then-MAC）信封可被解密 ——
    /// 手工构造合法 v3 信封（测试进程为 net8，经此用例确定性覆盖 DecryptCbcThenHmac 路径）。
    /// </summary>
    [Fact]
    public void AuthenticatedEncryption_CbcHmacEnvelope_RoundTrips()
    {
        var provider = CreateProvider();
        var key = Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng==");
        var plain = Encoding.UTF8.GetBytes("manual v3 envelope");

        var envelope = BuildCbcHmacEnvelope(key, plain, tamper: false);

        provider.DecryptBytes(envelope).Should().Equal(plain);
    }

    /// <summary>
    /// T-7.3 验收（续）：篡改 v3 信封密文体 → 常量时间 MAC 校验失败 → 抛 <see cref="CryptographicException"/>。
    /// </summary>
    [Fact]
    public void AuthenticatedEncryption_CbcHmacEnvelope_TamperedMac_ThrowsCryptographicException()
    {
        var provider = CreateProvider();
        var key = Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng==");
        var plain = Encoding.UTF8.GetBytes("manual v3 envelope");

        var envelope = BuildCbcHmacEnvelope(key, plain, tamper: true);

        var act = () => provider.DecryptBytes(envelope);

        act.Should().Throw<CryptographicException>();
    }

    /// <summary>
    /// 认证加密开启时拒绝裸 CBC 密文（无版本前缀）：抛 <see cref="CryptographicException"/> 而非静默解密。
    /// </summary>
    [Fact]
    public void AuthenticatedEncryption_RawCbcCipherText_IsRejected()
    {
        var legacyOptions = new AesEncryptionOptions
        {
            Key = Convert.FromBase64String("MTIzNDU2Nzg5MDEyMzQ1Ng=="),
            EnableAuthenticatedEncryption = false,
        };
        using var legacyProvider = new DefaultAesEncryptionProvider(Options.Create(legacyOptions));
        var rawCbc = legacyProvider.EncryptBytes(Encoding.UTF8.GetBytes("legacy"));

        var provider = CreateProvider();
        var act = () => provider.DecryptBytes(rawCbc);

        act.Should().Throw<CryptographicException>()
            .WithMessage("*版本前缀*");
    }

    /// <summary>构造 v3（CBC+HMAC）信封：<c>[0x03][IV(16)][MAC(32)][密文]</c>。</summary>
    private static byte[] BuildCbcHmacEnvelope(byte[] key, byte[] plain, bool tamper)
    {
        using var aes = Aes.Create();
        aes.Key = key;
        aes.Mode = CipherMode.CBC;
        aes.Padding = PaddingMode.PKCS7;
        aes.GenerateIV();

        byte[] cipher;
        using (var encryptor = aes.CreateEncryptor())
            cipher = encryptor.TransformFinalBlock(plain, 0, plain.Length);

        // MAC 覆盖 IV + 密文（Encrypt-then-MAC，与 DecryptCbcThenHmac 的 ComputeHmac 一致）
        byte[] mac;
        using (var hmac = new HMACSHA256(key))
            mac = hmac.ComputeHash(aes.IV.Concat(cipher).ToArray());

        var envelope = new byte[1 + aes.IV.Length + mac.Length + cipher.Length];
        envelope[0] = 0x03;
        Buffer.BlockCopy(aes.IV, 0, envelope, 1, aes.IV.Length);
        Buffer.BlockCopy(mac, 0, envelope, 1 + aes.IV.Length, mac.Length);
        Buffer.BlockCopy(cipher, 0, envelope, 1 + aes.IV.Length + mac.Length, cipher.Length);

        if (tamper)
            envelope[^1] ^= 0x01;
        return envelope;
    }

    #endregion
}
