// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026   
//  Mud.HttpUtils 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using System.Collections.Immutable;

namespace Mud.HttpUtils;

/// <summary>
/// 代码生成器基类。
/// </summary>
public abstract class TransitiveCodeGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public abstract void Initialize(IncrementalGeneratorInitializationContext context);

    protected const string CompilerGeneratedAttribute = GeneratedCodeConsts.CompilerGeneratedAttribute;
    protected string GeneratedCodeAttribute => GeneratedCodeConsts.HttpGeneratedCodeAttribute;


    /// <summary>
    /// 获取生成代码的默认引入的命名空间。
    /// </summary>
    /// <returns></returns>
    protected virtual Collection<string> GetFileUsingNameSpaces()
    {
        return ["System", "System.ComponentModel.DataAnnotations", "System.Runtime.CompilerServices", "System.Linq.Expressions"];
    }

    /// <summary>
    /// 根据注解名获取需要进行代码辅助生成的类。
    /// </summary>
    /// <param name="context"><see cref="IncrementalGeneratorInitializationContext"/>对象。</param>
    /// <param name="attributeNames">需要查找的特性名称数组。</param>
    /// <returns></returns>
    protected IncrementalValueProvider<ImmutableArray<T?>> GetClassDeclarationProvider<T>(IncrementalGeneratorInitializationContext context, string[] attributeNames) where T : TypeDeclarationSyntax
    {
        // 使用CompilationProvider来确保在设计时和编译时都能正确工作
        var compilationProvider = context.CompilationProvider;

        // 获取所有带有指定特性的类
        var generationInfo = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, c) => node is T typeDecl && typeDecl.AttributeLists.Count > 0,
                transform: (ctx, c) =>
                {
                    var classNode = (T)ctx.Node;

                    // 快速检查：如果没有特性，直接返回null
                    if (classNode.AttributeLists.Count == 0)
                        return null;

                    // 获取符号信息 - 使用Compilation确保设计时也能正常工作
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classNode, c);

                    // 如果SemanticModel无法获取符号，尝试使用Compilation
                    if (symbol == null)
                    {
                        return null;
                    }

                    // 检查是否有目标特性
                    var hasTargetAttribute = symbol.GetAttributes()
                        .Any(a => attributeNames.Contains(a.AttributeClass?.Name));

                    if (hasTargetAttribute)
                    {
                        return classNode;
                    }

                    return null;
                })
            .Where(static s => s is not null)
            .Collect();

        return generationInfo;
    }

    /// <summary>
    /// 生成通用的文件头部
    /// </summary>
    public void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 此代码由Mud源生成器自动生成，请勿手动修改");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");

        var usingNamespaces = GetFileUsingNameSpaces();
        foreach (var usingNamespace in usingNamespaces)
        {
            sb.AppendLine($"using {usingNamespace};");
        }
    }


    /// <summary>
    /// 获取XML文档注释
    /// </summary>
    protected string GetXmlDocumentation(SyntaxNode syntaxNode)
    {
        if (syntaxNode == null)
            return string.Empty;

        var leadingTrivia = syntaxNode.GetLeadingTrivia();
        var xmlDocTrivia = leadingTrivia.FirstOrDefault(t => t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
                                                             t.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia));

        if (xmlDocTrivia != default)
        {
            return xmlDocTrivia.ToFullString();
        }

        return string.Empty;
    }

    /// <summary>
    /// 报告生成错误的诊断信息
    /// </summary>
    /// <param name="context">源码生成上下文</param>
    /// <param name="descriptor">诊断描述符</param>
    /// <param name="className">类名</param>
    /// <param name="exception">异常信息</param>
    protected void ReportErrorDiagnostic(
        SourceProductionContext context,
        DiagnosticDescriptor descriptor,
        string className,
        Exception exception)
    {
        context.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, className, exception?.Message));
    }

}