// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026   
//  Mud.HttpUtils 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。使用本项目应遵守相关法律法规和许可证的要求。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

using System.Collections.Immutable;

namespace Mud.HttpUtils;

/// <summary>
/// 代码生成器基类。
/// </summary>
public abstract class TransitiveCodeGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public abstract void Initialize(IncrementalGeneratorInitializationContext context);

    protected const string CompilerGeneratedAttribute = GeneratedCodeConsts.CompilerGeneratedAttribute;
    protected static string GeneratedCodeAttribute => GeneratedCodeConsts.HttpGeneratedCodeAttribute;


    /// <summary>
    /// 获取生成代码的默认引入的命名空间。
    /// </summary>
    /// <returns></returns>
    /// <remarks>
    /// NEW-GEN-13 修复：原默认列表仅含 4 个命名空间，不包含生成代码实际依赖的
    /// System.Net.Http、System.Threading、System.Text.Json、Mud.HttpUtils 等。
    /// 若子类未重写此方法且消费项目未配置 GlobalUsings.cs，生成代码可能因缺少 using 而编译失败。
    /// 修复后扩展为生成代码实际依赖的完整命名空间集合。
    /// </remarks>
    protected virtual Collection<string> GetFileUsingNameSpaces()
    {
        return
        [
            "System",
            "System.Collections.Generic",
            "System.ComponentModel.DataAnnotations",
            "System.Linq",
            "System.Linq.Expressions",
            "System.Net.Http",
            "System.Runtime.CompilerServices",
            "System.Text.Json",
            "System.Text.Json.Serialization",
            "System.Threading",
            "System.Threading.Tasks",
            "Microsoft.Extensions.Logging",
            "Mud.HttpUtils",
            "Mud.HttpUtils.Observability"
        ];
    }

    /// <summary>
    /// 生成通用的文件头部
    /// </summary>
    public static void GenerateFileHeader(StringBuilder sb, IEnumerable<string> usingNamespaces)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 此代码由Mud源生成器自动生成，请勿手动修改");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");

        foreach (var usingNamespace in usingNamespaces)
        {
            sb.AppendLine($"using {usingNamespace};");
        }
    }

    /// <summary>
    /// 生成通用的文件头部（使用子类提供的命名空间）
    /// </summary>
    public void GenerateFileHeader(StringBuilder sb)
    {
        GenerateFileHeader(sb, GetFileUsingNameSpaces());
    }


    /// <summary>
    /// 获取XML文档注释
    /// </summary>
    protected string GetXmlDocumentation(SyntaxNode syntaxNode)
    {
        if (syntaxNode == null)
            return string.Empty;

        var leadingTrivia = syntaxNode.GetLeadingTrivia();
        var xmlDocTrivia = leadingTrivia.FirstOrDefault(t => t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
                                                             t.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia));

        if (xmlDocTrivia != default)
        {
            return xmlDocTrivia.ToFullString();
        }

        return string.Empty;
    }

    /// <summary>
    /// 报告生成错误的诊断信息（带精确位置）
    /// </summary>
    /// <param name="context">源码生成上下文</param>
    /// <param name="descriptor">诊断描述符</param>
    /// <param name="className">类名</param>
    /// <param name="exception">异常信息</param>
    /// <param name="location">错误位置</param>
    protected void ReportErrorDiagnostic(
        SourceProductionContext context,
        DiagnosticDescriptor descriptor,
        string className,
        Exception exception,
        Location location)
    {
        context.ReportDiagnostic(Diagnostic.Create(descriptor, location ?? Location.None, className, GeneratorDebugLogger.FormatExceptionMessage(exception)));
    }

}